services:
  - type: web
    name: brahma-disaster-management
    runtime: php
    buildCommand: bash ./deploy.sh
    startCommand: vendor/bin/heroku-php-apache2
    rootDir: .
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - "**/*.php"
        - "**/*.html"
        - "**/*.css"
        - "**/*.js"
        - "**/*.json"
        - "composer.*"
        - ".buildpacks"
        - ".render-buildpacks*"
        - "Procfile"
        - "deploy.sh"
      ignoredPaths:
        - "node_modules/**"
    envVars:
      - key: RENDER
        value: "true"
      - key: IS_RENDER
        value: "true"
      - key: SMTP_HOST
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
    buildFilter:
      paths:
        - "**/*.php"
        - "composer.*"
    healthCheckPath: /
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
  
databases:
  - name: brahma-disaster-db
    databaseName: brahma_db
    user: brahma_user
    plan: free
